name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ./scripts/audit.sh
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build css
        run: yarn css
      - name: Build js
        run: yarn js
      - name: Code style
        run: yarn pretty:check
      - name: Test
        run: yarn test
